version: '3.8'

services:
  app:
    build: .
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_HOST=db
      - DB_PORT=
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
